// This file is auto-generated by scripts/generate-mdx-index.js
// Do not edit manually - your changes will be overwritten!
// To add a new article, create a .mdx file in /content/writing/ and run: npm run generate-mdx

export const buildingBeforeYouFeelReady = `---
title: Building Before You Feel Ready
description: Why shipping imperfect projects taught me more than planning ever did.
publishDate: 21.Feb.2026
author: Gaurav Nardia
ogImage: https://gauravnardia.com/assets/og-images/building-before-ready.jpg
keywords: building in public, shipping fast, indie hacking, full stack developer
---


Most of the projects I’ve built didn’t start with confidence. They started with curiosity.

Trybit wasn’t built because I knew it would work. It was built because I wanted to see if I could design a real-time challenge system from scratch.

The HTTP Protocol project wasn’t built for production. It was built because I wanted to understand what actually happens under the hood when we type \`https://\`.

I’ve learned something important:

> You don’t become ready and then build.  
> You build, and that’s how you become ready.

## Shipping > Perfect Planning

For a long time, I believed I needed to:
- Know system design deeply  
- Master every edge case  
- Write “perfect” architecture  

Before shipping anything.

But every meaningful improvement in my skill came from:

- Breaking my own production code  
- Fixing performance issues at 2AM  
- Debugging real authentication bugs  
- Handling actual users, not test data  

There’s no substitute for real friction.


## What Shipping Taught Me

### 1. Systems Thinking

Building full-stack forces you to think in flows:

User → API → Database → Response → UI → State

Once you’ve wired everything end-to-end, abstractions start making sense.

### 2. Ownership Changes Everything

When you deploy something publicly, responsibility shifts.

You’re no longer coding for fun.  
You’re building for someone who might rely on it.

That mindset alone improves quality.

### 3. Momentum Beats Motivation

Motivation fades.  
Momentum compounds.

Small features shipped consistently > One “perfect” release that never happens.

## The Real Skill

The real skill isn’t knowing every framework.

It’s being comfortable:

- Starting messy  
- Iterating fast  
- Improving what exists  
- Shipping anyway  

That’s what helped me move from learning tutorials to building SaaS products.

And that’s what I’m continuing to optimize for.

---

If you’re waiting to feel ready,  
you probably already are.

Start building.`;

export const buyADomain = `---
title: Buy a Domain
description: The first thing you should do when starting a project is buy a domain. Not set up your tech stack. Not design your logo. Buy a domain. Here's why.
publishDate: 02.Dec.2025
author: Gaurav Nardia
ogImage: https://gauravnardia.com/assets/og-images/buy-a-domain.jpg
keywords: domain, buy domain, starting a project, web development, entrepreneurship
---

The first thing you should do when starting a project is buy a domain. Not set up your tech stack. Not design your logo. Buy a domain.

This sounds trivial. It costs \$12 a year. But most people don't do it. They tell themselves they'll do it later, after they validate the idea. They use a subdomain or some free hosting URL. And this tiny decision ends up costing them.

**When you buy a domain, something changes.** The project becomes real in a way it wasn't before. You've spent money, however small. You've committed to a name. You can't pretend anymore that this is just an idea you're toying with. This psychological shift matters. Ideas are cheap. Domains force you to take the next step. Once you own yourproject.com, you have to build something to put there. The domain sits in your account, quietly demanding that you do something with it.

You can't name things well under pressure. When you're rushing to launch, you pick whatever domain is available. Usually something with hyphens or random letters tacked on. Or worse, you launch with a temporary name and promise yourself you'll rebrand later. But rebranding is painful. You lose SEO. You confuse users. You have to update links everywhere. Better to spend an afternoon finding the right name now than spend months dealing with a name you settled for.

Buy the domain early and live with the name for a while. You'll know if it's right. And if it's not, you can change it before anyone knows the project exists.

You can't buy a domain without deciding what you're building. The name has to mean something. Is this a product? A service? A portfolio? The act of choosing forces you to think clearly about what this project actually is. Vague ideas stay vague until you have to describe them in a URL. "A platform for connecting creative professionals" becomes creativeconnect.com or networkforartists.com, and suddenly you realize you need to pick a lane. This is good. Clarity early saves time later.

No one takes myproject.webflow.io seriously. It signals you're not serious. It says this might disappear tomorrow, so why should anyone invest time in it? A real domain costs almost nothing but signals commitment. It tells people this isn't just a weekend experiment. You care enough to spend \$12 and figure out DNS. That's a low bar, but most people don't clear it.

This matters even more for portfolios. If you're a developer or designer showing your work, yourname.github.io doesn't compete with yourname.com. One looks professional. The other looks like homework.

Platforms change their rules. They raise prices. They shut down. When your project lives on someone else's domain, you're renting, not owning. **A domain is yours.** You can move it between hosts. You can redirect it anywhere. You can keep it for decades if you want. This permanence has value that compounds over time. Ten years from now, the links people shared to your site still work. The portfolio you sent to clients in 2025 still resolves. You own your corner of the internet.

The reason people don't buy domains early is that it feels premature. You don't have a product yet. You're not sure about the name. Maybe the whole idea won't work out. But that's exactly why you should do it now. When stakes are low, decisions are easier. You're not attached to anything yet. You can experiment with names. And if the project dies, you're out \$12. The cost of waiting is higher.

Good projects start with a domain. Not because the domain itself matters that much, but because buying it means you're starting. You're committing. You're making the idea real enough to name.

> So when you get that next idea, don't open your code editor first. Don't sketch wireframes. Open your domain registrar and find a name. Buy it. Then build something worth putting there.

The domain comes first. Everything else follows.
`;

export const deployFrontendOnAws = `---
title: Deploy Frontend on AWS
description: Step by step frontend deployment on AWS
author: Gaurav Nardia
publishDate: 20.Mar.2026
ogImage: https://gauravnardia.com/assets/og-images/deploy-frontend-on-aws.jpg
keywords: AWS, Deployment
---

Today I’m writing this because I don’t want to ever Google **“how to deploy frontend on AWS”** again. 

Every time I deploy, I forget one small thing, bucket policy, index.html, CloudFront settings… something always breaks. Then I go down the same rabbit hole.

So this is for my future self. If you’re reading this later: don’t think, just follow.

Overall flow will be **Build -> Upload to S3 -> Connect CloudFront -> Done**

Let's start it step by step.

**Step 1:**
Build the project by **npm run build** and copy all the files and folder of **dist.**

**Step 2:**
Create S3 bucket and name it and **Block all public access** while configuring it.

**Step 3:**
Open S3 bucket, Click Upload and Upload everything inside **dist.** **Not the dist folder, the files/folder inside it**

**Step 4:**
Go to CloudFront -> Create Distribution and set origin as your bucket and **Default root object = index.html**

**Step 5:**
Now Fix SPA routing **Go to Error Pages:** select 403 error code and set path **/index.html**

**Step 6:**
Save everything and cloudfront take 3-5 min to deploy. After deplyment successful, you will url like https://dxxxxx.cloudfront.net . This is the frontend deployed url.

**Step 7:**
Now add your custom domain. Go to cloudfront settings and add alternate domain. Now add DNS records and generate SSL certificate(ACM) and attach it in CloudFront

**Step 8:**
Also dont forget to add invalidation in cloudfront -> invalidations and set **Path: /*.** If you skip this then old website shows even after updation.`;

export const designIsTheMoat = `---
title: Design Is The Moat
description: Design is no longer a layer you add at the end. It is the product. And it's the moat that will matter most.
publishDate: 15.Nov.2025
modifiedDate: 26.Nov.2025
author: Gaurav Nardia
ogImage: https://gauravnardia.com/assets/og-images/design-is-the-moat.jpg
keywords: design, product design, AI, prototyping, startups
---

Over the last few days, I've been "vibe coding" some ideas. Building quick prototypes without overthinking. What surprised me wasn't how fast I could move, but how easy it has become to build something that actually works. Thanks to AI, spinning up fully functional tools and products is no longer reserved for engineers with years of experience. It's now possible for someone like me, a designer with a decent grasp of CSS and layout to ship production-ready apps/tools.

This is a paradigm shift!

AI has democratized building. You no longer need to be a 10x developer to launch a 10x product. The gap between an idea and a working prototype has collapsed. The tools are powerful, accessible, and fast. So naturally, we're entering a world where everyone will be able to build feature-rich products. Which means the bar is about to get much higher.

In this new world, code is not the moat. Design is.

If everyone can build features, what makes your product stand out isn't how many buttons it has. It's how it feels to use them. The clarity, the craftsmanship, the small moments of delight - all of that is design. And not just visual design, but the experience as a whole. From onboarding to micro-interactions to performance, design is what will separate products that get ignored from those that get loved.

> Code is becoming a commodity. Taste is not.

That's why design is the real moat. Not the kind you fake with a pretty landing page, but the kind that's baked into the product from the first click to the last detail. Design-led products are not just easier to use. They're harder to copy. Because fortunately or unfortunately, you can't fake taste.

This is where designers gain a massive advantage. Not only can they now build, they can build beautifully. With taste, empathy, and attention to the human side of software.

The future belongs to those who can ship, but more importantly, to those who can ship well-designed things. And in this new builder economy, design isn't just a skill. It's a moat.
`;

export const dockerForDevelopers = `---
title: Docker for developers
description: Docker end-to-end
publishDate: 13.Apr.2026
author: Gaurav Nardia
ogImage: https://gauravnardia.com/media/og-images/docker.jpg
keywords: docker, containers, docker-compose
---

In this article, we’ll talk about Docker end-to-end. First, **why do we even need Docker?** Imagine a new developer joins your team and you explain all the setup, dependencies, and versions. But they install the latest versions while your app depends on older ones. there will be dependency mismatch. Even if versions match, OS differences (Mac vs Windows) can still break things.

Instead of this messy setup, we use Docker. It lets you containerize your app so it runs the same way on any machine Without any issues.

There are few concepts in Docker that every developer should know. 

1. Image: This is just a blueprint of your app That contains code, dependencies, setup. 

2. Container: Container is the running instance of the image. This is where your actual app running. 

3. Dockerfile: A file where you define how your image should be built. In this, we configure what Docker image we are going to use, what dependency and how our app will run. 

4. Dockerhub: It is like GitHub but for Docker images, where we build our image and publish on it. 

These are the few concepts that everybody must know about Docker, and now we are going to write the first Dockerfile.

1. We will define our base image, like what image we are going to use, what is the base image in our product.
2. We define the working directory where our app should be initialized in the image.
3. We copy the package.json file first because of caching.
4. We install all the dependencies.
5. We copy all folder and files, etc.
6. We expose the command to run our project, like \`npm start\`. As shown in the picture 
![Docker](/assets/docker1.png)

After creating an image for our app, we can build it and push it to Docker Hub so that other developers can pull it and run our app directly. 
 - build cmd:- docker build -t my-app .
 - running image:- docker run -p 3000:3000 my-app

 **Docker Compose (for multiple services):** When we have multiple containers like postgres, node, bun, etc., then instead of starting each container manually, we create docker-compose. Docker-compose lets us run all the containers with a single command. This is the example of a docker compose file. Here we are running multiple services like Postgres, Redis, etc. 

 We can run all the services with a single command that is : **docker-compose up**
 ![Docker](/assets/docker2.png)

 **Docker Networking:** Before going into Docker networking, one thing to understand is that till now we were running a single container. But in real-world apps, we have multiple containers like backend, database, Redis, etc.

Now the question is how do they talk to each other? By default, every container is isolated. So they can’t communicate directly. This is where Docker networking comes in.

Docker networking allows containers to talk to each other using a network.

In Docker, each container gets its own IP, but we don’t use IPs because they change. Instead, we use container names.

**Example:**

First, create a network:
docker network create app-network

Run database:
docker run -d --name db --network app-network postgres

Run backend:
docker run -d --name backend --network app-network my-app

Now backend can talk to db using:
DB_HOST=db

**Docker Volumes:**
Now let’s talk about Docker volumes. By default, containers are temporary. If your container stops or gets deleted, all the data inside it is gone. This is a problem, especially for things like databases.

To solve this, we use volumes. Volumes are used to persist data outside the container. So even if the container is deleted, your data is safe.

**Example:**
docker run -v my-data:/data my-app

Here, my-data is volume.  and /data is path inside container. Now whatever is stored in /data will not be lost.

There are mainly two types:
1. Named Volumes
Docker manages them. docker run -v my-data:/data my-app

2. Bind Mounts
You link your local folder to container. docker run -v \$(pwd):/app my-app. It is used in development for live reload And syncing code.`;

export const growthWithoutHacks = `---
title: Growth Without Hacks
description: What really drives startup growth. Marketing isn't about shiny tools or growth hacks. It's about understanding people, solving their problems, and showing up consistently.
publishDate: 05.Nov.2025
modifiedDate: 26.Nov.2025
author: Gaurav Nardia
ogImage: https://gauravnardia.com/assets/og-images/growth-without-hacks.jpg
keywords: growth, marketing, startups, product development
---

We applied to YC once with the idea of Peerlist. Obviously did not get in. But that didn't stop us from applying Paul Graham's principles while building and growing Peerlist.

I don't need to explain how great PG's writing is—it's like the startup world's bible.
But do you know why it feels so relatable?
Because it's simple. And it's actionable. Every time I read it, I think, "Wait… I can actually do this!"

As Peerlist is growing and entering a new phase, I've been thinking a lot about "marketing." But to be honest, I'm not sure you can fully call it just marketing. It feels more like the way you operate your startup. The way you talk to users, the way you build, the way you grow.

After reading PG's essays again, I realized—we're already doing many of the things he talks about. That gave me a huge sense of validation and confidence to keep going.

Because yes, sometimes I do get distracted by shiny tactics—SEO hacks, paid ads, marketing funnels, etc.

But when you look at what actually makes startups successful, it's not tricks or hacks. It's simple. It's human. It's about building something people really want and staying close to your users.

Here are a few principles I've picked up from Paul Graham's writing and YC's way of building startups:

## Make a Few People Extremely Happy
In the early days of a startup, your goal is not to acquire thousands of users. Your goal is to make just a few people completely love your product.

When you have 10 users who can't live without what you've built, you're onto something real. These people become your evangelists. They give you thoughtful feedback, tell their friends, and sometimes even become your first paying customers or contributors.

Most startups fail not because they didn't get some users, but because they never got anyone who truly care. Aim for love, not lukewarm interest.

> "It's better to have 100 people who love you than 1,000 who sort of like you."

## Talk to Your Users. Really Talk to Them.
This one cannot be overstated: talk to your users. Not through forms or feedback widgets, actually talk to them. Schedule a 15-minute call. Message them directly. Ask them what's working, what's frustrating, and what they wish your product could do better.

These conversations will unlock insights that no analytics tool or A/B test can reveal. You'll learn how users describe your product in their own words. You'll see which parts of your product confuse them. You'll discover tiny frustrations that no metric would have ever exposed.

## Start Small, Go Deep
One of the most common early-stage startup mistakes is trying to appeal to everyone. The logic seems sound: a bigger market means a bigger opportunity, right?

But in reality, when you build for "everyone," you end up building something that resonates with no one. That is exactly why we solely focusing on "people in tech".

When you focus on solving one group's problems really well, your product becomes sharper, more useful, and more loved. From there, you can expand outward.

Airbnb didn't start by targeting the global travel market. They started by helping people find a place to stay during conferences. Stripe didn't start with "all payments"—they started with developers.

## Customer Support Is Marketing
Most people view customer support as a backend function. But in a startup, great support is one of your strongest marketing channels.

Why? Because early users remember how you made them feel. When you respond quickly, fix bugs promptly, or go out of your way to help, even for a single user, they'll remember it. And they'll talk about it.

It builds trust. It builds loyalty. And it creates stories worth sharing.

When a startup replies within minutes and solves your problem on a Sunday afternoon, it stands out. That's marketing.

## Measure What Matters
In the early stage, it's tempting to track everything: impressions, click-through rates, likes, followers, time on page. But most of these numbers don't matter if the fundamentals are broken.

What really matters? Usually just a handful of metrics: activation (are new users experiencing the core value?), retention (are they coming back?), and referrals (are they telling others?).

In last few months, we solely focused on retention. Because if people aren't coming back, nothing else matters.

## Grow Through Systems, Not Hacks
The internet loves the idea of "growth hacks". Shortcuts that magically skyrocket your users. But those spikes rarely last. I have experienced that!

Instead, real growth comes from building systems: talking to users every day, shipping small improvements regularly, refining your messaging, iterating on onboarding, and making the product better week after week.

It's slower, but far more sustainable. And over time, this compounding effort becomes your competitive advantage.

## Learn From People Who Say No
When someone doesn't sign up, doesn't return, or outright says "this isn't for me", don't ignore it. Ask them why.

Most people won't give feedback unless you ask. But when you do, you often hear the truth: maybe your onboarding was confusing, your messaging didn't make sense, or your product didn't solve a real pain.

Every "no" is an opportunity to learn, refine, and improve your product or positioning. The people who leave often teach you more than the ones who stay.

> Your most valuable feedback often comes from your harshest critics, not your biggest fans.

---

Marketing isn't about shiny tools or growth hacks. It's about understanding people, solving their problems, and showing up consistently.

So if you're building something today, don't ask: *How do I get more users?
Ask: How do I make the next 10 users love what I'm building?*

That's the real marketing strategy.

Highly recommend to read Paul Graham's [Startups in 13 Sentences](https://www.paulgraham.com/13sentences.html).
`;

export const iBuiltMyOwnAnalyticsTool = `---
title: I Built My Own Analytics Tool. Here's How and Why.
description: The story behind Puffin Analytics: why I built it, how the tracking script works, and what I learned building a SaaS from zero.
publishDate: 13.Mar.2026
author: Gaurav Nardia
ogImage: https://gauravnardia.com/assets/og-images/puffin-analytics.jpg
keywords: Analytics, Tool, builder, cracked engineer, SaaS
---

![Puffin Analytics](/assets/puffin-banner.png)

One day I was visiting [Peerlist's blog](https://peerlist.io/blog/engineering/best-website-analytics-tools-for-indie-hackers-and-developer) written by the **Akash Bhadange (Peerlist Founder)** and saw the name **Plausible** that caught my eye. I opened it and saw it's an analytics tool where we can see the traffic we are getting to our websites.

And then for few next day I saw different kind of analytics tool and tried some, but I don't know why I wasn't able to feel these tools, like some tools have bad UIs, some are expensive and don't look modern, and wherever I go to them, my mind says just exit it, **seriously.**

But that analytics core idea really excited me and really wanted to learn this technology, **How these analytics tools detect data from websites** so I decided to build an analytics tool in a way that makes users feel about the product, looks modern and affordable. So I learned the core technology to build this and then I started building [Puffin Analytics](https://puffinanalytics.com). I learned a lot about the analytics tool while building this.

**So I Started Building.**


First decision was the database. Analytics tools handle a LOT of writes, every page visit is an event. I needed something fast, scalable and affordable. I chose Neon(Postgres), I should choose Click House for this tool but I didn't have money to pay them. So I had to choose which is free and chose Neon(Postgres). I wanted to build **MVP** as soon as possible. And when it comes to MVP. Who can forget **Nextjs**. So I built this in Nextjs. These are the tech stack I used for V1 of **Puffin Analytics.**

The hardest part was the Tracking Script. This is the core of any analytics tool. Without this, nothing works. The tracking script is a small JavaScript snippet that users paste into their website's HTML with a **data-api-key** attribute tied to their site.

<script defer src="https://puffinanalytics.com/script" data-api-key="your_key"></script>

When the script loads, it reads the API key, captures the current page path, referrer, and user agent, then immediately fires an event to my "/api/event" endpoint using **navigator.sendBeacon,** which is perfect for analytics because it sends data asynchronously without blocking the page load or slowing down the user's experience. The interesting part was handling **SPA navigations.** In a normal website, every page load fires the script fresh. But in **Next.js** or **React apps**, the page doesn't actually reload when you navigate, just the URL changes. So I had to detect route manually. I did this polling "location.pathname" every 500ms and also listening to the popstate event. Whenever the path changes, it fires a new tracking event automatically.

I also handled referrer tracking smartly. If a user lands on your site from a **?ref=** query param (like from a newsletter or campaign link), it picks that up as the referrer instead of the browser's default referrer. This gives you much more accurate source tracking. 

Once real challenge I hit in production that the script URL as loading from [puffinanalytics.com](puffinanalytics.com) which was doing a 307 temporary redirect to [www.puffinanalytics.com](puffinanalytics.com). That meant every visitor was making two requests just to load the script. A user actually caught this in production and flagged it. I fixed it within minutes by updating the DNS A record and setting the correct production domain in Vercel. Shipping in public keeps you sharp.

## This is the  V1 Architecture (MVP).

Here's how data flows in Puffin Analytics from start to finish:
 
1. User pastes the script on their website
2. A visitor lands on their site and script fires instantly
3. Script sends a payload to /api/event with path, referrer and user agent
4. API validates the API key, identifies the site, parses the user agent for browser, OS and device info
5. Event gets stored in Neon Postgres
6. Dashboard queries the DB and shows the owner their traffic

This is Simple. No third party data brokers. No cookies. No GDPR headaches.

![Puffin Dashboard](/assets/og-images/puffin.png)
 
In V1, Puffin Analytics ships with:
 
- Visitor tracking
- Top pages, referrers, browsers, devices and countries
- Unique visitors vs total visits
- Clean, minimal dashboard that doesn't overwhelm you

## What I Learned and What's Next.
 
 - Building Puffin taught me more than any tutorial ever could. A few honest lessons that I learned Ship fast, fix in public. The 307 redirect bug was caught by a real user within hours of posting. That feedback loop is invaluable and humbling at the same time.
 - ClickHouse would have been better for analytics at scale but Neon got me to MVP fast and free. Right tool for the right stage.
 - People care about design. The first [comment](https://x.com/Ayda__gol/status/2032023492984541396?s=20) I got was *"love the design, well done."* Not the features. Not the tech stack. The feeling. That told me a lot.

In V2, I will focust on:
 - Robust bot filtering
 - Custom event tracking
 - Weekly email reports
 - Better performance at scale

 > Give [Puffin Analytics](https://puffinanalytics.com) a try.  Would love to hear what you think.`;

export const makeSomethingYouWant = `---
title: Make Something YOU Want
description: The best products come from personal frustration. When you build something you actually need, you understand the problem deeply, you know what's missing, and you have the motivation to make it great.
publishDate: 01.Nov.2025
modifiedDate: 26.Nov.2025
author: Gaurav Nardia
ogImage: https://gauravnardia.com/assets/og-images/make-something-you-want.jpg
keywords: product development, startups, entrepreneurship, design
---

We are builders. We always wants to build something. We have unlimited ideas. Which creates confusion. Confusion to the level that we end up building nothing!

Happens to every one of us where we can't decide on what to build. Maybe as a startup idea or even a simple side project.

I see a lot of posts on Peerlist as well, where people ask for ideas. My simple answer is always - build something you would use every day. This statement is not mine by the way. I read it, and it stuck with me.

Solve a simple problem for yourself. Be your own first user. It helps!

There are so many **[side projects](https://peerlist.io/launchpad)** launching on Peerlist every week. Most of the top projects are simple ideas with great execution solving a personal problem of that developer or designer. These side projects are the most loved ones. Because they are relatable.

When you build something for yourself, you are motivated to make it the best it can be. You know exactly what you need and what works for you. This personal touch makes your project more genuine and useful. Others who face the same problem will see the value in your solution.

Think about the tools and apps you use daily. Many of them started as small projects to solve a problem the creator faced. Gmail was created because the developers were frustrated with existing email services. Slack was built to solve communication issues within a team. These solutions were born out of necessity and grew into something much bigger.

By building something you would use, you create a strong foundation. Your passion and need drive you to keep improving it. You will find joy in using what you've built, and this satisfaction will fuel your drive to keep going.

So, the next time you're stuck on what to build, look inward. What problem do you face every day? What tool or service would make your life easier? Start there. Build it for yourself, and let others benefit from your solution.

In the end, the best projects come from a place of genuine need and personal experience. Build something you would use, and you'll find that others will want to use it too. Your simple, relatable solution might just become the next big thing.

Lastly - Here's Jack Dorsey on why building something for yourself can be better than trying to solve a problem.

<iframe width="560" height="315" src="https://www.youtube.com/embed/tA6MB1y1DDM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
`;

export const oauthAndPkce = `---
title: OAuth & PKCE
description: OAuth & PKCE Explained
author: Gaurav Nardia
publishDate: 10.Apr.2026
ogImage: https://gauravnardia.com/assets/og-images/oauth.jpg
keywords: Oauth, PKCE
---

In this article, I will write about OAuth and PKCE. What are these, and how these works? We will talk about them in detail.

OAuth basically is your application can use the third-party identity provider to log in. For example, we have seen on a lot of websites a button called "Sign in with Google", "Sign in with Microsoft", "Sign in with Apple" etc. These buttons are the protocols of OAuth.

But now you will think, why we need OAuth when we can use just email and password. The problem is that for email & password, we have to remember our email and password every time when we log in into apps with different IDs, And for email and password, we have to write the whole authentication system from scratch, and we have to handle a lot of security features.

But by Oauth, we don't need to remember our multiple passwords, and we don't have to worry about the security. Let's say, if we are doing sign in with Google, Google will handle it with security itself. You don't need to worry about the security. That's where OAuth comes into the picture. You just click the "Sign in with Google" button and you can just log in. 

Now, how does the OAuth flow work? Let's say we are doing sign in with Google. 
1. Go to [Google Console](https://console.cloud.google.com).
2. Register your app.
3. You will get client ID and secret after your app registration. 
4. Now integrate "sign in with Google" in your app by client ID and secret. 

Now let's talk about the flow when a user clicks the "Sign in with Google" button. It redirects to the accounts.google.com consent popup, appended with the client ID and redirect URI. When the user clicks the "Approve" button on the Google popup, it redirects back to the app with the code, which is a temporary, short-lived code. That short-lived code interacts with Google's backend. Our app's backend sends the code, Google Client ID, and secret together to Google's backend. Google backend verifies it, and if it's successful, it gives you an access token. You store it on your server and can access the user's information. 

You can see it in the diagram. 
![Oauth](/assets/oauth.png)

The problem happens with the client secret. We have to secure that because anyone can attack it and access our information. In this scenario, in the website application, the access token is stored on our server, so it is secured right now.

But when the app doesn't have a backend and it just has Google login, it is necessary to secure the client secret. What is the flow here? When our application doesn't have the backend:
1. When we click the Google button, it redirects to the consent form with the client ID and redirect URI and sends back the code.
2. If our application doesn't have the backend, we will store it in the client, but anyone can attack our client and get this code.

This is the exact problem that PKCE (proof key for code exchange) solves. 

In PKCE, when the user clicks the "Sign in with Google" button, it generates a new random code every time. The random code will be different for every click, and it encrypts it and makes it a code challenge. Let's say we encrypt it via SHAA256. It generates two codes: Original code and code challenge.

It redirects to a consent popup with the appended client ID, code challenge, and encryption algorithm. And when a user clicks the Approve button on the consent screen, then Google backend stores the code challenge, encryption algorithm, and original code. And give the client a code. 

Now, the client sends a request to the Google backend with the original code and the code that Google gave the client after clicking the Approve button. The Google backend decrypts the encrypted code that is stored in their backend, and if it matches the original code, it gives the access token.

That's how PKCE works, and that's how your client application is secured by PKCE(Proof key for code exchange ). 

`;

export const rateLimiting = `---
title: Rate Limiting
description: A practical guide to protecting APIs, controlling traffic, and designing scalable systems with rate limiting.
publishDate: 17.Mar.2026
author: Gaurav Nardia
ogImage: https://gauravnardia.com/assets/og-images/rate-limit.jpg
keywords: Rate Limiting, Architechture, Scaling, System Design
---

I implemented rate limiting in [Puffin analytics](https://puffinanalytics.com) and it made me realize there’s more depth to it than I initially thought. Writing this to properly understand it for myself.

Since Puffin is an analytics tool, anyone can hit the tracking endpoint repeatedly. Without limits, one bad actor (or even a bug) could flood the system.

In Puffin, rate limiting means controlling how many events a single source(user/IP/project) can send in a given time.

In Puffin this is the events flow without rate limiting:
![Diagram 1](/assets/puffin-flow-without-rate-limiting.png)

Without rate limiting redis can get flooded, Queue can lag, DB writes can spike, Overall system can become unstable. So I needed a way to control how fast request enter the system.

So what rate limiting means is putting a cap on how many requests a user (or client) can make in a given time. If they cross the limit, we simply reject the request.

I think of it like a bucket with tokens. Each user has a bucket with fixed token and token are added over time. Every request consumes one token. If there is no token left in the bucket, request is rejected. 

How to implement rate limiting in Puffin is I rate limit on the basis of user IP and Used Redis to store count. I used **Fixed Window Counter** approach in Puffin.  

How it works is it tracks every request from the IP. When the first event hits, it sets the expiry in Redis of 60 seconds, and let's say I allowed 100 requests per second. If the IP exceeds the 300 requests per 60 second, it blocks the request. And after every 60 seconds, the request resets.

After implementing the rate limiting in Puffin, I read more about it. I read about the different types of rate limiting. 

### Types of Rate Limiting

- Fixed Window Counter
- Token Bucket
- Sliding Window Log
- Leaky Bucket
- Sliding Window Counter

### Fixed Window Counter
In this, we count how many requests a user makes within a fixed time window (like 1 minute). For example, if the limit is 100 requests per minute, we allow requests until the counter reaches 100.

Once the limit is reached, any extra requests within that same window are rejected. When the time window resets, the counter also resets back to 0, and requests are allowed again.

The main issue is that it allows bursts at the boundary. For example, a user can send 100 requests at the end of one window and another 100 at the start of the next window, which can cause sudden spikes.
![Diagram 2](/assets/fix-window-counter.png)


### Token Bucket
Token bucket is basically a bucket with a fixed number of tokens that refill at a fixed rate of time.
![Diagram 2](/assets/bucket-token.png)
It's so simple to implement and memory efficient but bucket size and refill rate can be challenging to tune properly. 

### Sliding Window Log
Sliding window log works by storing each request with its timestamp. In this, every time a request comes in, we save its timestamp. Then, for each new request, we check how many requests were made in the last fixed duration (like the last 60 seconds).

We remove all the old requests that are outside this time window and only keep the recent ones. If the number of remaining requests is within the limit, we allow the request; otherwise, we reject it.

This way, the limit is always based on the actual last 60 seconds, not fixed time blocks, so it avoids burst issues. The downside is that it needs more memory because we have to store every request.
![Diagram 4](/assets/sliding-window-log.png)

### Leaky Bucket
Leaky bucket works on queue-based system. Requests are added into a bucket that has a fixed capacity. For example, if the bucket size is 10,000 requests, any new requests beyond that limit will overflow and get rejected. Requests don’t get processed immediately. Instead, they leave the bucket at a constant, fixed rate, like water leaking out. 

These requests then move forward and are processed steadily at that same rate. This way, even if a sudden burst of requests comes in, the system handles them smoothly without spikes.
![Diagram 3](/assets/leaky-bucket.png)

**The pros of this are:**
- its memory efficiency
- requests are processed at a fixed rate so it's suitable for use cases where the stable rate flow is needed. 

**The pros of this are:**
- Burst of traffic fills up the queue with old requests, and new requests will not proceed. 
- There are two parameters in this It might not be easy to tune it up properly. 

### Sliding Window Counter
Sliding window counter works by combining the current window and the previous window. In this, we don’t store every request like sliding window log. Instead, we just keep the count of requests in the current window and the previous one.

When a new request comes in, we calculate an approximate count by taking some part of the previous window’s requests (based on how much time has passed) and adding the current window’s requests. So instead of resetting everything like fixed window, the count changes smoothly over time.

This helps reduce the burst issue at the boundaries and gives a more balanced limit. It’s more accurate than fixed window and also doesn’t use too much memory.
![Diagram 4](/assets/sliding-window-counter.png)
`;

export const realTimeSystems = `---
title: Real-Time Systems — Quick Notes
description: The first thing you should do when starting a project is buy a domain. Not set up your tech stack. Not design your logo. Buy a domain. Here's why.
publishDate: 11.Apr.2026
author: Gaurav Nardia
ogImage: https://gauravnardia.com/assets/og-images/real-time.jpg
keywords: real-time, polling, sse, websockets
---

Real-time systems let your app update without refreshing. Instead of asking again and again, the client and server stay in sync in smarter ways.

3 core patterns of real-time systems:
 - Polling
 - Server-Sent Events (SSE)
 - WebSockets


**Polling:**
The client repeatedly asks the server “Any updates?” If the server has any kind of update, it will send it to that client. 

There are two types of polling:
1. Short polling
2. Long polling

In short polling client asks server at a fixed interval of time for updates, and server responds immediately, even if there is no data or update available. For example client sends a request to the server every 3 seconds, and the server responds immediately. It is very simple. The cons of short polling is wasteful request because if server has no data, it will respond as empty.

On the other hand, in long polling, the client sends a request to the server, and the server holds that request for a specific time until the data is available. Once the data is available, the server sends back the response to the client, and the client immediately sends the next request. The cons is the client has to start the new request every time.

**Server-Sent Events (SSE):**
In SSE the client sends the request to the server, the server keeps it open, and whenever the data is available, it just sends it to the client on the same request. in this only server can send data but client can't. This is one way. 


**WebSockets:**
It is a persistent two-way connection between client and server. It starts as an HTTP request, Make the connection, and it becomes open. As client and server both can send messages any time. But the cons is it is harder to scale. `;

export const reverseEngineering = `---
title: Reverse Engineering
description: Reverse engineering is not a hacker trick. It is the oldest and most honest way to understand how the world actually works.
publishDate: 022.Feb.2026
author: Gaurav Nardia
ogImage: https://gauravnardia.com/assets/og-images/reverse-engineering.jpg
keywords: Engineering, Reverse Engineering, builder, cracked engineer
---

There's a skill that almost nobody talks about in school, that the best hackers quietly consider one of the most important things you can learn. It's called reverse engineering. And once you understand what it really is, you'll realize it's not just a technical skill. It's a way of thinking.

**The simplest definition:** reverse engineering is figuring out how something works by taking it apart, rather than building it from scratch.

But that definition hides something interesting. When you reverse engineer something, you're not just learning what it does. You're learning why it was built the way it was. You're reading someone else's mind, someone who made a thousand decisions you never saw, and left traces of those decisions in the thing they built.

That's a very different kind of learning than reading a textbook.

Let's say you want to learn how a lock works. You could read a manual. Or you could pick one open yourself, feeling every pin click into place, understanding through your hands what diagrams could never quite teach you.

That's **reverse engineering**. And the person who picked the lock understands it in a way the person who read the manual simply doesn't.

Most people assume reverse engineering is something shady. It's not.

What I think is the most interesting thing about reverse engineering is it forces you to think about design in a way that building from scratch doesn't.

When you build something, you make decisions in a comfortable order. You start with a plan. You know your own assumptions. When you reverse engineer something, you inherit someone else's decisions without inheriting their reasoning. You have to reconstruct both.

This is humbling in a useful way. You realize how much of software design is invisible to the user. The choices that seem obvious in hindsight were hard-fought at the time. Every clever hack leaves a scar. Every shortcut compounds.

A person who has reverse engineered a lot of software develops an almost uncanny ability to read code they've never seen before. They know the patterns. They know what shortcuts look like. They know what code written under deadline pressure looks like versus code written by someone who had time to think.

**Reverse engineers** don't accept black boxes. They believe that everything made by humans can, in principle, be understood by humans. That there's no magic, just decisions made by other people, which can be reconstructed. That's a healthy way to think about the world.

The people who reverse engineer things, really reverse engineer them. They're not satisfied with "it works." They want to know why it works. And they're willing to do the hard, slow, unglamorous work of finding out.

> The people who built it had answers. Reverse engineering is how you find the questions they never wrote down.

It makes you better at everything.`;

export const stopFictionalCaseStudies = `---
title: Stop Writing Fictional Case Studies
description: Dear product designers, stop writing fictional case studies and start collaborating with developers on side projects to build credible proof-of-work.
publishDate: 26.Nov.2025
author: Gaurav Nardia
ogImage: https://gauravnardia.com/assets/og-images/stop-fictional-case-studies.jpg
keywords: product design, portfolio, case studies, collaboration, career advice
---
I have been noticing a growing trend in designers spending a lot of time working on fictional case studies. Where they come up with an imaginary solution, for some imaginary problem. It's useless, mostly!

If you want to be a UI designer, go ahead and do that. No issues. But if you're training yourself to be a product designer—continue reading.
We all know how difficult the job market is right now. Layoff news coming in from all sides. Early stage companies are hiring, but very conservatively. And if it's a designer role, you need to be more than extraordinary to make a cut because of the cut-throat competition. Especially for the entry level roles.

I am writing this piece of advice for the newcomers. The ones who are looking for their first design job. Folks, you are competing with designers with 2-4 years of experience. And your fictional case studies won't help to "stand out".
This essay is not about how to design your portfolio, it's very specific about your proof-of-work as a product designer.

So, **what** will help you to be exceptional?

Work on real problems, build real solutions for real users!

Now you will ask **how**?

Many developers launch their [side projects on Peerlist](https://peerlist.io/projects?ref=designgiri.com). Many of them need help with design. (Sorry devs, but you really do!)

Connect with them. Convince them. Show them how your designs make their project super useful. Collaborate with them. This is important. Collaborate.

Now the most important question — **WHY**?

Well, they are building something which will be used by real people. Not millions, but hundreds for sure. Help them validate the problem. Help them design the solution. Help them improve the aesthetics. Collaborate with them!

Trust me, these developers will help you become a better designer. They will teach you what "technical constraints" are and tell you the real meaning of "edge cases".

Now document your learnings after collaborating on this side project. Present it as a case study. It's your proof-of-work which is highly credible! Your design is functional in an actual browser or an app. Not just a screenshot in a fancy free mockup.

Imagine you're sitting in an interview and discussing all your learnings while building this project. Telling stories about how a simple copy change improved the conversion from a landing page. Talking about user research, unexpected insights and how you convinced the developer to implement that fancy animation.

As a hiring manager, I will "hard relate" to these stories. Because you are not only talking only about the outcome but the actual impact of your design.

Just find a developer who is working on a side project or share that you're open to collaboration. You just need one or two such projects on your portfolio. I am sure a design manager will be interested in chatting with you.

Because you will stand out!

All the best!

---

If you have read till here, I have 2 asks from you —
- Share this with your designer peers.
- Also read [portfolio advice](https://hvpandya.com/portfolio-advice?ref=designgiri.com) by [Hardik Pandya](https://peerlist.io/hardikpandya?ref=designgiri.com). It's a good one.
`;

export const systemDesignForBeginners = `---
title: System Design For Beginners
description: System design and all the system design components for beginners.
publishDate: 14.Mar.2026 
author: Gaurav Nardia
ogImage: https://gauravnardia.com/assets/og-images/systemdesign.jpg
keywords: System, Architechture, Scaling, System Design
---

Recently I started learning about system design. I thought it would be helpful to write blogs as I learn, so that in the future I can quickly revisit the concepts instead of going through everything from scratch again. So I'm writing this blog.

As a developer we usually focus on writing code , but rarely think about how a system handles thousands of million of users. System design is basically about building software that can scale, that can keep running smoothly even when a lot of people use them.

When we open a website, the browser sends a request to the server, and the server sends back a response to us.

If too many users send requests to a single server, then the server won't be able to handle the load and the server can crash. That's why we don't keep our software on a single server. We increase the number of servers.

**But then a second problem arises:** we have more than one server (many servers), but when a user sends a request, how do we decide which server we should send this request to?

This is where **Load Balancer** comes into the picture. A load balancer decides which server the request should be sent to. It sends the requests in a way that no single server becomes overloaded. In amazon/aws world this load balancer is called **ELB**(Elastic load balancer).

Now in **Microservice Architecture** we have many services like auth service, payment service, order service, etc. And each service has many servers as shown in the diagram:
![Diagram 1](/assets/systemdesignbeginners1.png)

So now I want when a requests goes to **/auth**, **/payment**, **/order** it must route to the auth service server, payment service server, and order service server respectively. But each service has many servers, so how do we manage it?

For resolving this, we add a load balancer for each service that handles the load for each service's servers.

Now we had 3 services and let's say we added 3 load balancers (one for each service). I want a host router that routes the requests to the respective load balancers. That host router is called API Gateway. It decides which service we should send a request to. It's a centralized entry point for API calls that acts as a reverse proxy that routes requests from the client to the backend service and back.
![Diagram 2](/assets/systemdesignbeginners2.png)

Now let's say a user pays and a payment service has to send the email of payment successful email to the user. **One way of doing this:** the user pays and the payment service triggers the email service (or we can say email worker). The email worker interacts with Gmail or any email provider and then sends the email to the user. After sending the email, the email worker tells the payment service that I have sent the email.

In this approach, the payment service has to wait because it takes time to send the email while interacting with third-party libraries. This is a synchronous approach. The payment service has to wait for 1 to 2 seconds to get the response from the email worker, and this is a synchronous way. In the case of a million users, we cannot hang the payment service on wait. Instead of a synchronous approach, we have to use the asynchronous approach.

**In asynchronous approach:** When user pays, payment service put the order in **queue(in aws this queue service is SQS - simple queue system)** and email worker pull events from queue and send the email and then it pulls next event and send email. And when email worker becomes overloaded, we can also scale it horizontally and increase the parallelism. 
![Diagram 3](/assets/systemdesignbeginners3.png)

But when we wanna send email, whatsapp message, sms on payment then we can use **PUB/SUB(one publisher and many subscribers can pull from it)** mechanism in AWS is called **SNS(simple notification system)**, when user pays payment service event to SNS and email, whatsapp, sms can pool from SNS. But in PUB/SUB there's no acknowledgement, when request fails of send notifications, we cant cope up with it. To prevent it, we use **Fan Out Mechanism.** In this SNS send events to queue and servers listen from queues. If some events fails we can put in queue and retry it.

ELB's also can be problematic thing, so for this, we use CDNs(in aws cloufront ) before LB's. These CDNs deploy machines in every region, it makes req-res so fast because whenever user send request, it goes to their nearest CDN and also caches the stuff and return it so fast.

These are some of the basic building blocks of system design. Things like load balancers, API gateways, queues, pub/sub, and CDNs help systems handle large numbers of users without breaking.

I'm still learning system design, and this blog is just my way of documenting what I learn. In future blogs, I'll try to go deeper into other system design concepts.`;

export const tryingToBeHuman = `---
title: Trying to Be Human
description: Why human creation will matter more, not less, in an age of infinite AI-generated content.
publishDate: 07.Dec.2025
author: Gaurav Nardia
ogImage: https://gauravnardia.com/assets/og-images/trying-to-be-human.jpg
keywords: AI, creativity, human creation, photography, analog, authenticity, artificial intelligence, digital age
---

I've been loading film cameras lately. Not because I need to, or because the pictures are better, but because there's something about the mechanical click of the advance lever that feels like proof of presence. Last week, standing on a street corner in Pune, I watched a family arrange themselves for a photo. They took seventeen versions with their phone, each one instantly reviewable, instantly deletable, instantly forgettable. I took one frame. It cost me money. I won't see it for days. I might have missed the moment entirely.

This is an absurd way to make photographs in 2025, and I know it. But absurdity might be the point.

We're entering a period where the question "Was this made by a person?" will become as important as "Is this any good?" They used to be the same question. They're not anymore. You can generate a sunset photograph that would have taken [Ansel Adams](https://www.anseladams.com/) three days of hiking and perfect timing. You can produce it in seconds, all before breakfast. The image might be beautiful. But it wasn't witnessed. No one stood there in the cold, waiting for the light.

**For most of human history, creation was evidence of experience.** A painting meant someone looked at that landscape. A photograph meant you were there. The thing and the making of it were inseparable. Now they're not. We've figured out how to have the thing without the making, the output without the input, the result without the experience.

**The internet promised us unlimited access to human creativity. What we're getting instead is unlimited access to the appearance of human creativity.** An AI can write in the style of Joan Didion, compose in the manner of Mozart, paint like Vermeer. It can do all of this without understanding a single word, note, or brushstroke. And for most purposes, that's enough.

Except it isn't.

I wrote an article recently. It got a good response. People shared it, told me they liked it. But twice, in different contexts, someone asked: "ChatGPT?" The question landed differently than criticism would have. It wasn't "this is bad" or "I disagree." It was "did you actually write this?" The content was the same either way, but the question had poisoned it. The meaning had collapsed before we could even discuss the ideas.

This is the world we're building. One where the first question isn't "What does this mean?" but "Who made this?"

**And here's what I think happens next: human-made things become precious exactly because they're scarce.**

When your kid draws a picture of your house, you don't hang it on the refrigerator because it's architecturally accurate. You hang it there because they made it, because the wonky perspective and the purple sun mean they were thinking about where you live and what it looks like to them. If you ran their drawing through an AI upscaler that fixed all the proportions, you'd have a better image and a worthless artifact.

We think we want art for its aesthetic properties, but what we actually want is evidence of human attention. **The struggle is the point. The difficulty is the signal.**

This is why analog photography, vinyl records, handwritten letters, and mechanical watches are having their moment. Not because they're superior technologies, but because they require human participation. They're inefficient by design. That inefficiency is a feature.

**The flood of AI-generated content will make human creation more valuable, not less.** When everything is abundant, scarcity becomes the premium. What cuts through is the thing that required presence, the thing that couldn't exist without someone being there to make it.

Film makes me hesitate. Before I press the shutter, I have to decide if this moment is worth the chemical space it will occupy. When the scans come back, there's always a small shock of recognition. These aren't perfectly composed, algorithmically optimized images. They're what I saw, translated through chemistry and my own imperfect judgment. The mistakes are mine. The successes are mine. The whole thing exists because I was there.

That's what we're going to need more of. Not just in photography, but in everything. Things that couldn't exist without someone being present to create them. Work that carries the signature of human limitation and human choice.

We're not going back to a world before AI. But we are entering a world where being human, being present, being the one who actually made the thing, will matter more than it has in a long time.

Making choices that require my judgment. Creating things that couldn't exist without my particular attention. Accepting that what I make will be imperfect, limited, unmistakably mine.
`;

// Map of all articles
export const allMDXContent: Record<string, string> = {
  'building-before-you-feel-ready': buildingBeforeYouFeelReady,
  'buy-a-domain': buyADomain,
  'deploy-frontend-on-aws': deployFrontendOnAws,
  'design-is-the-moat': designIsTheMoat,
  'docker-for-developers': dockerForDevelopers,
  'growth-without-hacks': growthWithoutHacks,
  'i-built-my-own-analytics-tool': iBuiltMyOwnAnalyticsTool,
  'make-something-you-want': makeSomethingYouWant,
  'oauth-and-pkce': oauthAndPkce,
  'rate-limiting': rateLimiting,
  'real-time-systems': realTimeSystems,
  'reverse-engineering': reverseEngineering,
  'stop-fictional-case-studies': stopFictionalCaseStudies,
  'system-design-for-beginners': systemDesignForBeginners,
  'trying-to-be-human': tryingToBeHuman,
};
